server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/triphub_payment
    username: triphub
    password: triphub
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
