package com.triphub.shared.common;

import static org.junit.jupiter.api.Assertions.*;

import java.time.LocalDateTime;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

@DisplayName("BaseEntity")
class BaseEntityTest {

    private static class ConcreteEntity extends BaseEntity {
        // Concrete implementation for testing abstract class
    }

    @Test
    @DisplayName("Should initialize with generated UUID id")
    void testEntityInitialization() {
        // Arrange & Act
        ConcreteEntity entity = new ConcreteEntity();
        
        // Assert - createdAt is initialized via field default, id and updatedAt are null (set by JPA on persist)
        assertNull(entity.getId());  // ID is generated by JPA on persist, not in constructor
        assertNotNull(entity.getCreatedAt());  // createdAt is initialized via field default value
        assertNull(entity.getUpdatedAt());  // updatedAt is nullable and starts as null
    }

    @Test
    @DisplayName("Should set createdAt timestamp on construction")
    void testCreatedAtTimestamp() {
        // Arrange
        LocalDateTime beforeCreation = LocalDateTime.now();
        
        // Act
        ConcreteEntity entity = new ConcreteEntity();
        LocalDateTime afterCreation = LocalDateTime.now();
        
        // Assert
        assertNotNull(entity.getCreatedAt());
        assertFalse(entity.getCreatedAt().isBefore(beforeCreation.minusSeconds(1)));
        assertFalse(entity.getCreatedAt().isAfter(afterCreation.plusSeconds(1)));
    }

    @Test
    @DisplayName("Should allow setting id")
    void testSetId() {
        // Arrange
        ConcreteEntity entity = new ConcreteEntity();
        String newId = "test-uuid-123";
        
        // Act
        entity.setId(newId);
        
        // Assert
        assertEquals(newId, entity.getId());
    }

    @Test
    @DisplayName("Should allow setting createdAt")
    void testSetCreatedAt() {
        // Arrange
        ConcreteEntity entity = new ConcreteEntity();
        LocalDateTime newCreatedAt = LocalDateTime.of(2020, 1, 1, 0, 0, 0);
        
        // Act
        entity.setCreatedAt(newCreatedAt);
        
        // Assert
        assertEquals(newCreatedAt, entity.getCreatedAt());
    }

    @Test
    @DisplayName("Should allow setting updatedAt")
    void testSetUpdatedAt() {
        // Arrange
        ConcreteEntity entity = new ConcreteEntity();
        LocalDateTime updatedTime = LocalDateTime.of(2025, 6, 15, 14, 30, 0);
        
        // Act
        entity.setUpdatedAt(updatedTime);
        
        // Assert
        assertEquals(updatedTime, entity.getUpdatedAt());
    }

    @Test
    @DisplayName("Should allow updatedAt to be null initially")
    void testUpdatedAtInitiallyNull() {
        // Arrange & Act
        ConcreteEntity entity = new ConcreteEntity();
        
        // Assert
        assertNull(entity.getUpdatedAt());
    }

    @Test
    @DisplayName("Should support getter and setter for all fields")
    void testAllGettersSetters() {
        // Arrange
        ConcreteEntity entity = new ConcreteEntity();
        String testId = "test-id";
        LocalDateTime createdTime = LocalDateTime.of(2020, 1, 1, 0, 0);
        LocalDateTime updatedTime = LocalDateTime.of(2025, 6, 15, 10, 30);
        
        // Act
        entity.setId(testId);
        entity.setCreatedAt(createdTime);
        entity.setUpdatedAt(updatedTime);
        
        // Assert
        assertEquals(testId, entity.getId());
        assertEquals(createdTime, entity.getCreatedAt());
        assertEquals(updatedTime, entity.getUpdatedAt());
    }

    @Test
    @DisplayName("Should maintain separate createdAt and updatedAt timestamps")
    void testCreatedAtAndUpdatedAtAreDifferent() {
        // Arrange
        ConcreteEntity entity = new ConcreteEntity();
        LocalDateTime createdTime = entity.getCreatedAt();
        
        // Act
        LocalDateTime updatedTime = LocalDateTime.now().plusHours(1);
        entity.setUpdatedAt(updatedTime);
        
        // Assert
        assertNotEquals(createdTime, updatedTime);
        assertEquals(createdTime, entity.getCreatedAt());
        assertEquals(updatedTime, entity.getUpdatedAt());
    }
}
